def outcome_on_validate(self):
    self.q1_apr_jun_target = float(self.get('apr_target') or 0) + float(self.get('may_target') or 0) + float(self.get('jun_target') or 0)
    self.q2_jul_sep_target = float(self.get('jul_target') or 0) + float(self.get('aug_target') or 0) + float(self.get('sep_target') or 0)
    self.q3_oct_dec_target = float(self.get('oct_target') or 0) + float(self.get('nov_target') or 0) + float(self.get('dec_target') or 0)
    self.q4_jan_mar_target = float(self.get('jan_target') or 0) + float(self.get('feb_target') or 0) + float(self.get('mar_target') or 0)
    self.total_target = float(self.get('q1_apr_jun_target') or 0) + float(self.get('q2_jul_sep_target') or 0) + float(self.get('q3_oct_dec_target') or 0) + float(self.get('q4_jan_mar_target') or 0)
    self.q1_apr_jun_achievement = float(self.get('apr_achievement') or 0) + float(self.get('may_achievement') or 0) + float(self.get('jun_achievement') or 0)
    self.q2_jul_sep_achievement = float(self.get('jul_achievement') or 0) + float(self.get('aug_achievement') or 0) + float(self.get('sep_achievement') or 0)
    self.q3_oct_dec_achievement = float(self.get('oct_achievement') or 0) + float(self.get('nov_achievement') or 0) + float(self.get('dec_achievement') or 0)
    self.q4_jan_mar_achievement = float(self.get('jan_achievement') or 0) + float(self.get('feb_achievement') or 0) + float(self.get('mar_achievement') or 0)
    self.total_achievement = float(self.get('q1_apr_jun_achievement') or 0) + float(self.get('q2_jul_sep_achievement') or 0) + float(self.get('q3_oct_dec_achievement') or 0) + float(self.get('q4_jan_mar_achievement') or 0)